name: Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '8'

      - name: Compile java class
        run: |
          cd data/jvm8
          javac User.java
          javac GaussTest.java

      - name: Cargo build and test
        run: |
          cargo build
          cargo test